// app/animaux/[id]/page.tsx
"use client"

import { useEffect, useState } from "react"
import { useParams, useRouter } from "next/navigation"
import { ArrowLeft, Dog, Cat, CalendarDays, User, Phone, MessageCircle, Instagram, Mail, MapPin, Clock, Sparkles, PawPrint } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import Image from "next/image"

interface Garde {
  id: string
  typeAnimal: string
  nomAnimal: string
  nomClient: string
  contact?: string
  source?: string
  dateDebut: string
  dateFin: string
  duree?: string
  tarif: number
  typeGarde: string
  statut: string
  notes?: string
  photos: string[]
  isShared: boolean
  profile: {
    name: string
  }
}

const ContactIcon = ({ type }: { type: string }) => {
  const iconClass = "h-4 w-4"
  switch (type) {
    case "phone":
      return <Phone className={iconClass} />
    case "whatsapp":
      return <MessageCircle className={iconClass} />
    case "instagram":
      return <Instagram className={iconClass} />
    case "email":
      return <Mail className={iconClass} />
    default:
      return <Phone className={iconClass} />
  }
}

const parseContact = (contact: string) => {
  if (!contact) return { type: "phone", value: "" }
  const [type, ...valueParts] = contact.split(":")
  return { type, value: valueParts.join(":") }
}

export default function GardeDetailPage() {
  const params = useParams()
  const router = useRouter()
  const [garde, setGarde] = useState<Garde | null>(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    const fetchGarde = async () => {
      try {
        const response = await fetch(`/api/gardes/${params.id}`)
        if (response.ok) {
          const data = await response.json()
          setGarde(data)
        } else {
          console.error("Erreur lors de la récupération de la garde")
        }
      } catch (error) {
        console.error("Erreur:", error)
      } finally {
        setLoading(false)
      }
    }

    if (params.id) {
      fetchGarde()
    }
  }, [params.id])

  if (loading) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-rose-50 via-pink-50 to-violet-50 flex items-center justify-center">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-rose-500"></div>
      </div>
    )
  }

  if (!garde) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-rose-50 via-pink-50 to-violet-50 flex items-center justify-center">
        <div className="text-center">
          <h2 className="text-2xl font-bold text-slate-800 mb-4">Garde introuvable</h2>
          <Button onClick={() => router.push("/animaux")} variant="outline">
            <ArrowLeft className="h-4 w-4 mr-2" />
            Retour à la liste
          </Button>
        </div>
      </div>
    )
  }

  const contact = parseContact(garde.contact || "")
  const statusColors = {
    confirmé: { bg: "bg-green-100", text: "text-green-800", border: "border-green-300" },
    en_cours: { bg: "bg-blue-100", text: "text-blue-800", border: "border-blue-300" },
    terminé: { bg: "bg-slate-100", text: "text-slate-800", border: "border-slate-300" },
    annulé: { bg: "bg-red-100", text: "text-red-800", border: "border-red-300" }
  }
  const currentStatut = statusColors[garde.statut as keyof typeof statusColors] || statusColors.confirmé

  return (
    <div className="min-h-screen bg-gradient-to-br from-rose-50 via-pink-50 to-violet-50">
      {/* Header */}
      <div className="sticky top-0 z-10 bg-white/80 backdrop-blur-lg border-b border-slate-200">
        <div className="max-w-4xl mx-auto px-4 py-4 flex items-center gap-3">
          <Button
            onClick={() => router.push("/animaux")}
            variant="ghost"
            size="icon"
            className="rounded-full"
          >
            <ArrowLeft className="h-5 w-5" />
          </Button>
          <div className="flex items-center gap-2 flex-1">
            {garde.typeAnimal.toLowerCase() === "chien" ? (
              <Dog className="h-5 w-5 text-slate-600" />
            ) : (
              <Cat className="h-5 w-5 text-slate-600" />
            )}
            <h1 className="text-xl font-bold text-slate-800 truncate">{garde.nomAnimal}</h1>
          </div>
          <div className={`px-3 py-1.5 rounded-full text-xs font-semibold ${currentStatut.bg} ${currentStatut.text} border ${currentStatut.border}`}>
            {garde.statut === "confirmé" ? "Confirmé" : garde.statut === "en_cours" ? "En cours" : garde.statut === "terminé" ? "Terminé" : "Annulé"}
          </div>
        </div>
      </div>

      {/* Content */}
      <div className="max-w-4xl mx-auto px-4 py-6 space-y-4">
        {/* Badge créateur */}
        <div className="flex justify-center">
          <span className={`px-3 py-1.5 rounded-full text-xs font-semibold shadow-sm ${
            garde.isShared
              ? "bg-gradient-to-r from-purple-400 to-violet-400 text-white"
              : garde.profile.name === "jordan"
                ? "bg-gradient-to-r from-blue-400 to-indigo-400 text-white"
                : "bg-gradient-to-r from-rose-400 to-pink-400 text-white"
          }`}>
            {garde.isShared ? "Garde partagée JJ" : `Garde de ${garde.profile.name === "jordan" ? "Jordan" : "Juliette"}`}
          </span>
        </div>

        {/* Photos */}
        {garde.photos && garde.photos.length > 0 && (
          <Card className="overflow-hidden border-0 shadow-lg">
            <CardContent className="p-0">
              {garde.photos.length === 1 ? (
                <div className="relative w-full h-64 sm:h-96">
                  <Image
                    src={garde.photos[0]}
                    alt={garde.nomAnimal}
                    fill
                    className="object-cover"
                  />
                </div>
              ) : (
                <div className="grid grid-cols-2 gap-2 p-2">
                  {garde.photos.map((photo, index) => (
                    <div key={index} className="relative aspect-square rounded-lg overflow-hidden">
                      <Image
                        src={photo}
                        alt={`${garde.nomAnimal} - Photo ${index + 1}`}
                        fill
                        className="object-cover"
                      />
                    </div>
                  ))}
                </div>
              )}
            </CardContent>
          </Card>
        )}

        {/* Tarif */}
        <Card className="border-0 shadow-lg bg-gradient-to-r from-rose-500 to-pink-500 text-white">
          <CardContent className="p-6">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <Sparkles className="h-5 w-5" />
                <span className="text-sm font-medium">Tarif de la garde</span>
              </div>
              <div className="text-3xl font-bold">{garde.tarif} €</div>
            </div>
          </CardContent>
        </Card>

        {/* Informations principales */}
        <Card className="border-0 shadow-lg">
          <CardContent className="p-6 space-y-4">
            <h2 className="text-lg font-bold text-slate-800 flex items-center gap-2">
              <PawPrint className="h-5 w-5 text-rose-500" />
              Informations
            </h2>

            <div className="space-y-3">
              <div className="flex items-start gap-3">
                {garde.typeAnimal.toLowerCase() === "chien" ? (
                  <Dog className="h-5 w-5 text-slate-400 mt-0.5 flex-shrink-0" />
                ) : (
                  <Cat className="h-5 w-5 text-slate-400 mt-0.5 flex-shrink-0" />
                )}
                <div>
                  <p className="text-xs text-slate-500">Type d'animal</p>
                  <p className="text-sm font-medium text-slate-800">{garde.typeAnimal}</p>
                </div>
              </div>

              <div className="flex items-start gap-3">
                <User className="h-5 w-5 text-slate-400 mt-0.5 flex-shrink-0" />
                <div>
                  <p className="text-xs text-slate-500">Client</p>
                  <p className="text-sm font-medium text-slate-800">{garde.nomClient}</p>
                </div>
              </div>

              {contact.value && (
                <div className="flex items-start gap-3">
                  <ContactIcon type={contact.type} />
                  <div>
                    <p className="text-xs text-slate-500">Contact</p>
                    <p className="text-sm font-medium text-slate-800">{contact.value}</p>
                  </div>
                </div>
              )}

              {garde.source && (
                <div className="flex items-start gap-3">
                  <MapPin className="h-5 w-5 text-slate-400 mt-0.5 flex-shrink-0" />
                  <div>
                    <p className="text-xs text-slate-500">Source</p>
                    <p className="text-sm font-medium text-slate-800">{garde.source}</p>
                  </div>
                </div>
              )}

              <div className="flex items-start gap-3">
                <CalendarDays className="h-5 w-5 text-slate-400 mt-0.5 flex-shrink-0" />
                <div>
                  <p className="text-xs text-slate-500">Type de garde</p>
                  <p className="text-sm font-medium text-slate-800">{garde.typeGarde}</p>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Dates */}
        <Card className="border-0 shadow-lg">
          <CardContent className="p-6 space-y-4">
            <h2 className="text-lg font-bold text-slate-800 flex items-center gap-2">
              <CalendarDays className="h-5 w-5 text-rose-500" />
              Période
            </h2>

            <div className="space-y-3">
              <div className="flex items-center gap-3">
                <Clock className="h-5 w-5 text-slate-400 flex-shrink-0" />
                <div className="flex-1">
                  <p className="text-xs text-slate-500">Du</p>
                  <p className="text-sm font-medium text-slate-800">
                    {new Date(garde.dateDebut).toLocaleDateString("fr-FR", {
                      weekday: 'long',
                      year: 'numeric',
                      month: 'long',
                      day: 'numeric'
                    })}
                  </p>
                </div>
              </div>

              <div className="flex items-center gap-3">
                <Clock className="h-5 w-5 text-slate-400 flex-shrink-0" />
                <div className="flex-1">
                  <p className="text-xs text-slate-500">Au</p>
                  <p className="text-sm font-medium text-slate-800">
                    {new Date(garde.dateFin).toLocaleDateString("fr-FR", {
                      weekday: 'long',
                      year: 'numeric',
                      month: 'long',
                      day: 'numeric'
                    })}
                  </p>
                </div>
              </div>

              {garde.duree && (
                <div className="mt-3 p-3 bg-slate-50 rounded-lg">
                  <p className="text-xs text-slate-500">Durée</p>
                  <p className="text-sm font-semibold text-slate-800">{garde.duree}</p>
                </div>
              )}
            </div>
          </CardContent>
        </Card>

        {/* Notes */}
        {garde.notes && (
          <Card className="border-0 shadow-lg">
            <CardContent className="p-6">
              <h2 className="text-lg font-bold text-slate-800 mb-3">Notes</h2>
              <p className="text-sm text-slate-600 whitespace-pre-wrap">{garde.notes}</p>
            </CardContent>
          </Card>
        )}
      </div>
    </div>
  )
}

// apps/web/app/pages/animaux/[id]/index.vue
<script setup lang="ts">
import { useAnimaux, type Garde } from "../../../features/animaux/composables/useAnimaux";

definePageMeta({
  middleware: ["authenticated"],
});

const route = useRoute();
const router = useRouter();
const { getGarde } = useAnimaux();

const garde = ref<Garde | null>(null);
const loading = ref(true);

onMounted(async () => {
  try {
    const id = route.params.id as string;
    garde.value = await getGarde(id);
  } catch (error) {
    console.error("Failed to fetch garde", error);
  } finally {
    loading.value = false;
  }
});

function formatCurrency(amount: number) {
  return new Intl.NumberFormat('fr-FR', {
    style: 'currency',
    currency: 'EUR',
  }).format(amount);
}

function formatDate(date: Date | string) {
  return new Date(date).toLocaleDateString("fr-FR", {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });
}

function getStatutColor(statut: string) {
  switch (statut) {
    case "confirmé":
      return "from-blue-400 to-indigo-500";
    case "en_cours":
      return "from-amber-400 to-orange-500";
    case "terminé":
      return "from-emerald-400 to-teal-500";
    case "annulé":
      return "from-red-400 to-rose-500";
    default:
      return "from-slate-400 to-slate-500";
  }
}

function getStatutLabel(statut: string) {
  switch (statut) {
    case "confirmé":
      return "Confirmé";
    case "en_cours":
      return "En cours";
    case "terminé":
      return "Terminé";
    case "annulé":
      return "Annulé";
    default:
      return statut;
  }
}

function goBack() {
  router.push("/animaux");
}

function navigateToEdit() {
  router.push(`/animaux/${route.params.id}/edit`);
}
</script>

<template>
  <div class="px-4 pb-4 sm:px-6 sm:pb-6">
    <div class="mx-auto max-w-2xl">
      <!-- Loading state -->
      <div v-if="loading" class="flex justify-center py-12">
        <div class="h-10 w-10 sm:h-12 sm:w-12 animate-spin rounded-full border-4 border-purple-300 border-t-purple-600"></div>
      </div>

      <!-- Not found state -->
      <div v-else-if="!garde" class="text-center py-12 backdrop-blur-xl bg-white/10 border border-white/20 rounded-2xl">
        <h3 class="text-lg font-bold text-white mb-2">Garde introuvable</h3>
        <button
          @click="goBack"
          class="mt-4 px-4 py-2 rounded-lg backdrop-blur-xl bg-white/10 border border-white/20 text-white font-medium transition-all hover:bg-white/15"
        >
          ← Retour à la liste
        </button>
      </div>

      <!-- Content -->
      <div v-else class="space-y-4">
        <!-- Header -->
        <div class="flex items-center justify-between mb-6">
          <button
            @click="goBack"
            class="px-3 py-2 rounded-lg backdrop-blur-xl bg-white/10 border border-white/20 text-white text-sm transition-all hover:bg-white/15"
          >
            ← Retour
          </button>
          <button
            @click="navigateToEdit"
            class="px-4 py-2 rounded-lg bg-gradient-to-r from-blue-400 to-indigo-400 text-white font-semibold shadow-md transition-all active:scale-95"
          >
            Éditer
          </button>
        </div>

        <!-- Badge partagé -->
        <div v-if="garde.isShared" class="flex justify-center">
          <span class="inline-block px-3 py-1.5 rounded-full text-xs font-semibold bg-gradient-to-r from-purple-400 to-violet-400 text-white shadow-md">
            Garde partagée
          </span>
        </div>

        <!-- Nom et statut -->
        <div class="backdrop-blur-xl bg-white/10 border border-white/20 rounded-2xl p-6">
          <div class="flex items-start justify-between gap-4">
            <div class="flex items-center gap-4">
              <div class="w-16 h-16 rounded-full bg-gradient-to-br from-rose-400 to-pink-400 flex items-center justify-center shrink-0">
                <svg class="w-8 h-8 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M14.828 14.828a4 4 0 01-5.656 0M9 10h.01M15 10h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
              </div>
              <div>
                <h1 class="text-2xl font-bold text-white">{{ garde.nomAnimal }}</h1>
                <p class="text-sm text-slate-300">{{ garde.typeAnimal }}</p>
              </div>
            </div>
            <div :class="`px-3 py-1.5 rounded-full text-xs font-semibold bg-gradient-to-r ${getStatutColor(garde.statut)} text-white shadow-md`">
              {{ getStatutLabel(garde.statut) }}
            </div>
          </div>
        </div>

        <!-- Tarif -->
        <div class="backdrop-blur-xl bg-gradient-to-r from-rose-500/50 to-pink-500/50 border border-white/20 rounded-2xl p-6">
          <div class="flex items-center justify-between">
            <div class="flex items-center gap-2">
              <svg class="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
              </svg>
              <span class="text-sm font-medium text-white">Tarif de la garde</span>
            </div>
            <div class="text-3xl font-bold text-white">{{ formatCurrency(garde.tarif) }}</div>
          </div>
        </div>

        <!-- Informations principales -->
        <div class="backdrop-blur-xl bg-white/10 border border-white/20 rounded-2xl p-6 space-y-4">
          <h2 class="text-lg font-bold text-white flex items-center gap-2">
            <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
            Informations
          </h2>

          <div class="space-y-3">
            <div class="flex items-start gap-3">
              <svg class="w-5 h-5 text-slate-400 mt-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
              </svg>
              <div>
                <p class="text-xs text-slate-400">Client</p>
                <p class="text-sm font-medium text-white">{{ garde.nomClient }}</p>
              </div>
            </div>

            <div v-if="garde.contact" class="flex items-start gap-3">
              <svg class="w-5 h-5 text-slate-400 mt-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z" />
              </svg>
              <div>
                <p class="text-xs text-slate-400">Contact</p>
                <p class="text-sm font-medium text-white">{{ garde.contact }}</p>
              </div>
            </div>

            <div v-if="garde.source" class="flex items-start gap-3">
              <svg class="w-5 h-5 text-slate-400 mt-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" />
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 11a3 3 0 11-6 0 3 3 0 016 0z" />
              </svg>
              <div>
                <p class="text-xs text-slate-400">Source</p>
                <p class="text-sm font-medium text-white">{{ garde.source }}</p>
              </div>
            </div>

            <div class="flex items-start gap-3">
              <svg class="w-5 h-5 text-slate-400 mt-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
              </svg>
              <div>
                <p class="text-xs text-slate-400">Type de garde</p>
                <p class="text-sm font-medium text-white">{{ garde.typeGarde }}</p>
              </div>
            </div>
          </div>
        </div>

        <!-- Dates -->
        <div class="backdrop-blur-xl bg-white/10 border border-white/20 rounded-2xl p-6 space-y-4">
          <h2 class="text-lg font-bold text-white flex items-center gap-2">
            <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
            </svg>
            Période
          </h2>

          <div class="space-y-3">
            <div class="flex items-center gap-3">
              <svg class="w-5 h-5 text-slate-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
              </svg>
              <div class="flex-1">
                <p class="text-xs text-slate-400">Du</p>
                <p class="text-sm font-medium text-white">{{ formatDate(garde.dateDebut) }}</p>
              </div>
            </div>

            <div class="flex items-center gap-3">
              <svg class="w-5 h-5 text-slate-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
              </svg>
              <div class="flex-1">
                <p class="text-xs text-slate-400">Au</p>
                <p class="text-sm font-medium text-white">{{ formatDate(garde.dateFin) }}</p>
              </div>
            </div>

            <div v-if="garde.duree" class="mt-3 p-3 backdrop-blur-xl bg-white/5 border border-white/10 rounded-lg">
              <p class="text-xs text-slate-400">Durée</p>
              <p class="text-sm font-semibold text-white">{{ garde.duree }}</p>
            </div>
          </div>
        </div>

        <!-- Notes -->
        <div v-if="garde.notes" class="backdrop-blur-xl bg-white/10 border border-white/20 rounded-2xl p-6">
          <h2 class="text-lg font-bold text-white mb-3">Notes</h2>
          <p class="text-sm text-slate-300 whitespace-pre-wrap">{{ garde.notes }}</p>
        </div>
      </div>
    </div>
  </div>
</template>
