// apps/web/app/pages/budget/[year]/[month]/index.vue
<script setup lang="ts">
import { useBudget } from "../../../../features/budget/composables/useBudget";
import { useProfiles } from "../../../../features/profiles/composables/useProfiles";

definePageMeta({
  middleware: ["authenticated"],
});

const route = useRoute();
const year = parseInt(route.params.year as string);
const month = parseInt(route.params.month as string);

const { getMonthDetails, createExpense, updateExpense, deleteExpense, createIncome } = useBudget();
const { selectedProfile, loadSelectedProfile } = useProfiles();

const data = ref<{
  expenses: any[];
  incomes: any[];
  categories: any[];
} | null>(null);
const loading = ref(true);

const monthNames = [
  "Janvier", "Février", "Mars", "Avril", "Mai", "Juin",
  "Juillet", "Août", "Septembre", "Octobre", "Novembre", "Décembre"
];

async function loadData() {
  loading.value = true;
  try {
    data.value = await getMonthDetails(year, month);
  } catch (error) {
    console.error("Failed to fetch month details", error);
  } finally {
    loading.value = false;
  }
}

onMounted(async () => {
  loadSelectedProfile();
  if (!selectedProfile.value) {
    navigateTo("/profiles");
    return;
  }
  await loadData();
});

const totalExpenses = computed(() => {
  return data.value?.expenses.reduce((sum, e) => sum + e.amount, 0) || 0;
});

const totalIncomes = computed(() => {
  return data.value?.incomes.reduce((sum, i) => sum + i.amount, 0) || 0;
});

const balance = computed(() => totalIncomes.value - totalExpenses.value);

const expenseCategories = computed(() => {
  return data.value?.categories.filter(c => c.type === "expense") || [];
});

function getExpensesByCategory(categoryId: string) {
  return data.value?.expenses.filter(e => e.categoryId?.toString() === categoryId) || [];
}

const showAddExpense = ref(false);
const showAddIncome = ref(false);
const showEditExpense = ref(false);
const selectedExpense = ref<any>(null);

const expandedCategories = ref<Set<string>>(new Set());
const expensesExpanded = ref(false);
const incomesExpanded = ref(false);

function toggleCategory(categoryId: string) {
  if (expandedCategories.value.has(categoryId)) {
    expandedCategories.value.delete(categoryId);
  } else {
    expandedCategories.value.add(categoryId);
  }
}

function isCategoryExpanded(categoryId: string) {
  return expandedCategories.value.has(categoryId);
}

const newExpense = reactive({
  description: "",
  amount: 0,
  categoryId: "",
  date: new Date().toISOString().split('T')[0],
});

const newIncome = reactive({
  description: "",
  amount: 0,
  date: new Date().toISOString().split('T')[0],
});

async function handleAddExpense() {
  try {
    const day = newExpense.date?.split('-')[2] || '01';
    await createExpense({
      ...newExpense,
      date: new Date(`${year}-${month.toString().padStart(2, '0')}-${day}`).toISOString(),
    });
    showAddExpense.value = false;
    newExpense.description = "";
    newExpense.amount = 0;
    newExpense.categoryId = "";
    await loadData();
  } catch (error) {
    console.error("Failed to create expense", error);
  }
}

async function handleAddIncome() {
  try {
    const day = newIncome.date?.split('-')[2] || '01';
    await createIncome({
      ...newIncome,
      date: new Date(`${year}-${month.toString().padStart(2, '0')}-${day}`).toISOString(),
    });
    showAddIncome.value = false;
    newIncome.description = "";
    newIncome.amount = 0;
    await loadData();
  } catch (error) {
    console.error("Failed to create income", error);
  }
}

function openEditExpense(expense: any) {
  selectedExpense.value = {
    ...expense,
    date: new Date(expense.date).toISOString().split('T')[0],
  };
  showEditExpense.value = true;
}

async function handleUpdateExpense() {
  if (!selectedExpense.value) return;
  try {
    const day = selectedExpense.value.date?.split('-')[2] || '01';
    await updateExpense(selectedExpense.value.id, {
      description: selectedExpense.value.description,
      amount: selectedExpense.value.amount,
      categoryId: selectedExpense.value.categoryId,
      date: new Date(`${year}-${month.toString().padStart(2, '0')}-${day}`).toISOString(),
    });
    showEditExpense.value = false;
    selectedExpense.value = null;
    await loadData();
  } catch (error) {
    console.error("Failed to update expense", error);
  }
}

async function handleDeleteExpense() {
  if (!selectedExpense.value) return;
  if (!confirm('Supprimer cette dépense ?')) return;
  try {
    await deleteExpense(selectedExpense.value.id);
    showEditExpense.value = false;
    selectedExpense.value = null;
    await loadData();
  } catch (error) {
    console.error("Failed to delete expense", error);
  }
}

</script>

<template>
  <div class="px-4 pb-4 sm:px-6 sm:pb-6">
    <div class="mx-auto max-w-6xl">
      <header class="mb-6">
        <NuxtLink to="/budget" class="mb-3 inline-flex items-center gap-2 text-sm text-slate-400 hover:text-white transition-colors">
          <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7" />
          </svg>
          Retour
        </NuxtLink>
        <h1 class="text-2xl sm:text-3xl font-bold text-purple-300">{{ monthNames[month - 1] }} {{ year }}</h1>
      </header>

      <div v-if="loading" class="flex justify-center py-12">
        <div class="h-10 w-10 sm:h-12 sm:w-12 animate-spin rounded-full border-4 border-purple-300 border-t-purple-600"></div>
      </div>

      <div v-else>
        <div class="mb-6 grid gap-3 sm:gap-4 sm:grid-cols-3">
          <div class="backdrop-blur-xl bg-white/5 border border-white/10 rounded-2xl p-4 sm:p-6">
            <p class="text-xs sm:text-sm font-medium text-slate-400">Revenus</p>
            <p class="mt-2 text-xl sm:text-2xl font-bold text-emerald-400">{{ totalIncomes.toFixed(2) }} €</p>
          </div>
          <div class="backdrop-blur-xl bg-white/5 border border-white/10 rounded-2xl p-4 sm:p-6">
            <p class="text-xs sm:text-sm font-medium text-slate-400">Dépenses</p>
            <p class="mt-2 text-xl sm:text-2xl font-bold text-rose-400">{{ totalExpenses.toFixed(2) }} €</p>
          </div>
          <div class="backdrop-blur-xl bg-white/5 border border-white/10 rounded-2xl p-4 sm:p-6">
            <p class="text-xs sm:text-sm font-medium text-slate-400">Solde</p>
            <p class="mt-2 text-xl sm:text-2xl font-bold" :class="balance >= 0 ? 'text-emerald-400' : 'text-rose-400'">
              {{ balance.toFixed(2) }} €
            </p>
          </div>
        </div>

        <div class="space-y-4">
          <section class="backdrop-blur-xl bg-white/5 border border-white/10 rounded-xl overflow-hidden">
            <button
              @click="incomesExpanded = !incomesExpanded"
              class="w-full flex items-center justify-between p-4 sm:p-5 transition-colors hover:bg-white/5"
            >
              <div class="flex items-center gap-3">
                <svg
                  class="w-5 h-5 transition-transform text-emerald-400"
                  :class="{ 'rotate-90': incomesExpanded }"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" />
                </svg>
                <h2 class="text-lg sm:text-xl font-bold text-white">💰 Revenus</h2>
              </div>
              <div class="flex items-center gap-3">
                <span class="text-sm sm:text-base font-semibold text-emerald-400">
                  +{{ totalIncomes.toFixed(2) }} €
                </span>
                <button
                  @click.stop="showAddIncome = true"
                  class="rounded-lg bg-emerald-600 hover:bg-emerald-700 px-3 py-1.5 text-xs sm:text-sm font-semibold text-white transition-all active:scale-95"
                >
                  + Ajouter
                </button>
              </div>
            </button>

            <div v-if="incomesExpanded" class="px-4 sm:px-5 pb-4 space-y-2 border-t border-white/10 pt-3">
              <div
                v-for="income in data?.incomes"
                :key="income.id"
                class="flex items-center justify-between text-sm"
              >
                <span class="text-slate-400">{{ income.description }}</span>
                <span class="font-semibold text-emerald-400">+{{ income.amount.toFixed(2) }} €</span>
              </div>
              <div v-if="!data?.incomes || data.incomes.length === 0" class="text-center py-4">
                <p class="text-sm text-slate-500">Aucun revenu</p>
              </div>
            </div>
          </section>

          <section class="backdrop-blur-xl bg-white/5 border border-white/10 rounded-xl overflow-hidden">
            <button
              @click="expensesExpanded = !expensesExpanded"
              class="w-full flex items-center justify-between p-4 sm:p-5 transition-colors hover:bg-white/5"
            >
              <div class="flex items-center gap-3">
                <svg
                  class="w-5 h-5 transition-transform text-rose-400"
                  :class="{ 'rotate-90': expensesExpanded }"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" />
                </svg>
                <h2 class="text-lg sm:text-xl font-bold text-white">💸 Dépenses</h2>
              </div>
              <div class="flex items-center gap-3">
                <span class="text-sm sm:text-base font-semibold text-rose-400">
                  -{{ totalExpenses.toFixed(2) }} €
                </span>
                <button
                  @click.stop="showAddExpense = true"
                  class="rounded-lg bg-rose-600 hover:bg-rose-700 px-3 py-1.5 text-xs sm:text-sm font-semibold text-white transition-all active:scale-95"
                >
                  + Ajouter
                </button>
              </div>
            </button>

            <div v-if="expensesExpanded" class="px-4 sm:px-5 pb-4 space-y-2 border-t border-white/10 pt-3">
              <div class="space-y-2 sm:space-y-3">
                <div v-for="category in expenseCategories" :key="category.id" class="backdrop-blur-xl bg-white/5 border border-white/10 rounded-xl overflow-hidden">
                  <button
                    @click="toggleCategory(category.id)"
                    class="w-full flex items-center justify-between p-3 sm:p-4 transition-colors hover:bg-white/5"
                  >
                    <div class="flex items-center gap-2">
                      <svg
                        class="w-4 h-4 transition-transform text-slate-400"
                        :class="{ 'rotate-90': isCategoryExpanded(category.id) }"
                        fill="none"
                        stroke="currentColor"
                        viewBox="0 0 24 24"
                      >
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" />
                      </svg>
                      <h3 class="text-sm sm:text-base font-semibold text-white">{{ category.name }}</h3>
                    </div>
                    <span class="text-xs sm:text-sm font-semibold text-rose-400">
                      -{{ getExpensesByCategory(category.id).reduce((sum, e) => sum + e.amount, 0).toFixed(2) }} €
                    </span>
                  </button>

                  <div v-if="isCategoryExpanded(category.id)" class="px-3 sm:px-4 pb-3 space-y-1.5 sm:space-y-2 border-t border-white/10 pt-2">
                    <button
                      v-for="expense in getExpensesByCategory(category.id)"
                      :key="expense.id"
                      @click="openEditExpense(expense)"
                      class="w-full flex items-center justify-between text-xs sm:text-sm py-2 px-2 rounded-lg hover:bg-white/5 active:bg-white/10 transition-colors"
                    >
                      <span class="text-slate-400">{{ expense.description }}</span>
                      <span class="font-semibold text-rose-400">-{{ expense.amount.toFixed(2) }} €</span>
                    </button>
                  </div>
                </div>

                <div v-if="expenseCategories.length === 0" class="backdrop-blur-xl bg-white/5 border border-white/10 rounded-xl p-6 sm:p-8 text-center">
                  <p class="text-sm text-slate-500">Aucune catégorie de dépenses</p>
                </div>
              </div>
            </div>
          </section>
        </div>
      </div>
    </div>

    <div v-if="showAddExpense" class="fixed inset-0 z-50 flex items-end sm:items-center justify-center bg-black/60 backdrop-blur-sm" @click.self="showAddExpense = false">
      <div class="w-full sm:max-w-md rounded-t-3xl sm:rounded-2xl backdrop-blur-xl bg-white/5 border-t sm:border border-white/10 p-5 sm:p-6 shadow-2xl max-h-[85vh] overflow-y-auto">
        <h3 class="mb-4 text-lg sm:text-xl font-bold text-rose-300">Nouvelle dépense</h3>
        <form @submit.prevent="handleAddExpense" class="space-y-3 sm:space-y-4">
          <div>
            <label class="text-xs sm:text-sm font-medium text-slate-300">Description</label>
            <input v-model="newExpense.description" required class="mt-1 w-full rounded-lg bg-white/5 border border-white/10 px-3 sm:px-4 py-2 text-sm sm:text-base text-white placeholder-slate-500 focus:border-rose-400 focus:outline-none" />
          </div>
          <div>
            <label class="text-xs sm:text-sm font-medium text-slate-300">Montant (€)</label>
            <input v-model.number="newExpense.amount" type="number" step="0.01" required class="mt-1 w-full rounded-lg bg-white/5 border border-white/10 px-3 sm:px-4 py-2 text-sm sm:text-base text-white placeholder-slate-500 focus:border-rose-400 focus:outline-none" />
          </div>
          <div>
            <label class="text-xs sm:text-sm font-medium text-slate-300">Catégorie <span class="text-rose-400">*</span></label>
            <select v-model="newExpense.categoryId" required class="mt-1 w-full rounded-lg bg-white/5 border border-white/10 px-3 sm:px-4 py-2 text-sm sm:text-base text-white focus:border-rose-400 focus:outline-none">
              <option value="" disabled class="bg-slate-800">Sélectionner une catégorie</option>
              <option v-for="cat in expenseCategories" :key="cat.id" :value="cat.id" class="bg-slate-800">{{ cat.name }}</option>
            </select>
          </div>
          <div class="flex gap-2 sm:gap-3 pt-2">
            <button type="submit" :disabled="!newExpense.categoryId" class="flex-1 rounded-lg bg-linear-to-r from-rose-600 to-red-600 py-2 text-sm sm:text-base font-semibold text-white transition-all active:scale-95 disabled:opacity-40 disabled:cursor-not-allowed">
              Créer
            </button>
            <button type="button" @click="showAddExpense = false" class="flex-1 rounded-lg bg-white/10 border border-white/20 py-2 text-sm sm:text-base font-semibold text-slate-300 transition-all active:scale-95">
              Annuler
            </button>
          </div>
        </form>
      </div>
    </div>

    <div v-if="showAddIncome" class="fixed inset-0 z-50 flex items-end sm:items-center justify-center bg-black/60 backdrop-blur-sm" @click.self="showAddIncome = false">
      <div class="w-full sm:max-w-md rounded-t-3xl sm:rounded-2xl backdrop-blur-xl bg-white/5 border-t sm:border border-white/10 p-5 sm:p-6 shadow-2xl max-h-[85vh] overflow-y-auto">
        <h3 class="mb-4 text-lg sm:text-xl font-bold text-emerald-300">Nouveau revenu</h3>
        <form @submit.prevent="handleAddIncome" class="space-y-3 sm:space-y-4">
          <div>
            <label class="text-xs sm:text-sm font-medium text-slate-300">Description</label>
            <input v-model="newIncome.description" required class="mt-1 w-full rounded-lg bg-white/5 border border-white/10 px-3 sm:px-4 py-2 text-sm sm:text-base text-white placeholder-slate-500 focus:border-emerald-400 focus:outline-none" />
          </div>
          <div>
            <label class="text-xs sm:text-sm font-medium text-slate-300">Montant (€)</label>
            <input v-model.number="newIncome.amount" type="number" step="0.01" required class="mt-1 w-full rounded-lg bg-white/5 border border-white/10 px-3 sm:px-4 py-2 text-sm sm:text-base text-white placeholder-slate-500 focus:border-emerald-400 focus:outline-none" />
          </div>
          <div class="flex gap-2 sm:gap-3 pt-2">
            <button type="submit" class="flex-1 rounded-lg bg-linear-to-r from-emerald-600 to-green-600 py-2 text-sm sm:text-base font-semibold text-white transition-all active:scale-95">
              Créer
            </button>
            <button type="button" @click="showAddIncome = false" class="flex-1 rounded-lg bg-white/10 border border-white/20 py-2 text-sm sm:text-base font-semibold text-slate-300 transition-all active:scale-95">
              Annuler
            </button>
          </div>
        </form>
      </div>
    </div>

    <div v-if="showEditExpense && selectedExpense" class="fixed inset-0 z-50 flex items-end sm:items-center justify-center bg-black/60 backdrop-blur-sm" @click.self="showEditExpense = false">
      <div class="w-full sm:max-w-md rounded-t-3xl sm:rounded-2xl backdrop-blur-xl bg-white/5 border-t sm:border border-white/10 p-5 sm:p-6 shadow-2xl max-h-[85vh] overflow-y-auto">
        <div class="flex items-center justify-between mb-4">
          <h3 class="text-lg sm:text-xl font-bold text-rose-300">Modifier la dépense</h3>
          <button @click="showEditExpense = false" class="w-8 h-8 flex items-center justify-center rounded-full hover:bg-white/10 transition-colors">
            <svg class="w-5 h-5 text-slate-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>
        <form @submit.prevent="handleUpdateExpense" class="space-y-4">
          <div>
            <label class="text-sm font-medium text-slate-300">Description</label>
            <input v-model="selectedExpense.description" required class="mt-1.5 w-full rounded-lg bg-white/5 border border-white/10 px-4 py-3 text-base text-white placeholder-slate-500 focus:border-rose-400 focus:outline-none" />
          </div>
          <div>
            <label class="text-sm font-medium text-slate-300">Montant (€)</label>
            <input v-model.number="selectedExpense.amount" type="number" step="0.01" required class="mt-1.5 w-full rounded-lg bg-white/5 border border-white/10 px-4 py-3 text-base text-white placeholder-slate-500 focus:border-rose-400 focus:outline-none" />
          </div>
          <div>
            <label class="text-sm font-medium text-slate-300">Catégorie</label>
            <select v-model="selectedExpense.categoryId" required class="mt-1.5 w-full rounded-lg bg-white/5 border border-white/10 px-4 py-3 text-base text-white focus:border-rose-400 focus:outline-none">
              <option value="" disabled class="bg-slate-800">Sélectionner une catégorie</option>
              <option v-for="cat in expenseCategories" :key="cat.id" :value="cat.id" class="bg-slate-800">{{ cat.name }}</option>
            </select>
          </div>
          <div class="flex flex-col gap-2 pt-2">
            <button type="submit" class="w-full rounded-lg bg-linear-to-r from-rose-600 to-red-600 py-3 text-base font-semibold text-white transition-all active:scale-95">
              Enregistrer
            </button>
            <button type="button" @click="handleDeleteExpense" class="w-full rounded-lg bg-red-600/20 border border-red-500/30 py-3 text-base font-semibold text-red-400 transition-all active:scale-95">
              Supprimer
            </button>
            <button type="button" @click="showEditExpense = false" class="w-full rounded-lg bg-white/10 border border-white/20 py-3 text-base font-semibold text-slate-300 transition-all active:scale-95">
              Annuler
            </button>
          </div>
        </form>
      </div>
    </div>

  </div>
</template>

// app/budget/[year]/[month]/page.tsx
"use client"

import { useState, useEffect } from "react"
import { useRouter, useParams } from "next/navigation"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Plus, TrendingUp, TrendingDown, DollarSign } from "lucide-react"
import Header from "@/components/header"

interface BudgetIncome {
  id: string
  description: string
  amount: number
  date: string
}

interface BudgetCategory {
  id: string
  name: string
  color?: string
  icon?: string
  total: number
}

const MONTH_NAMES = [
  "Janvier", "Février", "Mars", "Avril", "Mai", "Juin",
  "Juillet", "Août", "Septembre", "Octobre", "Novembre", "Décembre"
]

export default function BudgetMonthPage() {
  const router = useRouter()
  const params = useParams()
  const year = params.year as string
  const month = parseInt(params.month as string)
  const [profileId, setProfileId] = useState<string>("")
  const [monthId, setMonthId] = useState<string>("")
  const [incomes, setIncomes] = useState<BudgetIncome[]>([])
  const [categories, setCategories] = useState<BudgetCategory[]>([])
  const [loading, setLoading] = useState(true)
  const [showIncomeForm, setShowIncomeForm] = useState(false)
  const [showCategoryForm, setShowCategoryForm] = useState(false)
  const [newIncome, setNewIncome] = useState({ description: "", amount: "" })
  const [newCategory, setNewCategory] = useState({ name: "", color: "#10b981" })

  useEffect(() => {
    const initializeProfile = async (profileName: string) => {
      try {
        await fetch("/api/init", { method: "POST" })
        const profilesRes = await fetch("/api/profiles")
        const profilesList = await profilesRes.json()
        const currentProfile = profilesList.find((p: { name: string; id: string }) => p.name === profileName)

        if (currentProfile) {
          setProfileId(currentProfile.id)
          loadMonthData()
        }
      } catch (error) {
        console.error("Error initializing profile:", error)
        setLoading(false)
      }
    }

    const currentProfile = localStorage.getItem("currentProfile")
    if (!currentProfile) {
      router.push("/")
    } else {
      initializeProfile(currentProfile)
    }
  }, [router])

  const loadMonthData = async () => {
    try {
      const response = await fetch(`/api/budget/years/${year}/months/${month}`)
      if (response.ok) {
        const data = await response.json()
        setMonthId(data.monthId)
        setIncomes(data.incomes)
        setCategories(data.categories)
      }
    } catch (error) {
      console.error("Error loading month data:", error)
    } finally {
      setLoading(false)
    }
  }

  const handleAddIncome = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!newIncome.description || !newIncome.amount) return

    try {
      const response = await fetch(`/api/budget/incomes`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          description: newIncome.description,
          amount: parseFloat(newIncome.amount),
          monthId,
          profileId,
          date: new Date().toISOString(),
        }),
      })

      if (response.ok) {
        setNewIncome({ description: "", amount: "" })
        setShowIncomeForm(false)
        loadMonthData()
      }
    } catch (error) {
      console.error("Error adding income:", error)
    }
  }

  const handleAddCategory = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!newCategory.name) return

    try {
      const response = await fetch(`/api/budget/categories`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          name: newCategory.name,
          color: newCategory.color,
          monthId,
        }),
      })

      if (response.ok) {
        setNewCategory({ name: "", color: "#10b981" })
        setShowCategoryForm(false)
        loadMonthData()
      }
    } catch (error) {
      console.error("Error adding category:", error)
    }
  }

  const handleDeleteIncome = async (incomeId: string) => {
    if (!confirm("Supprimer cette entrée ?")) return

    try {
      const response = await fetch(`/api/budget/incomes/${incomeId}`, {
        method: "DELETE",
      })

      if (response.ok) {
        loadMonthData()
      }
    } catch (error) {
      console.error("Error deleting income:", error)
    }
  }

  const totalIncome = incomes.reduce((sum, income) => sum + income.amount, 0)
  const totalExpenses = categories.reduce((sum, cat) => sum + cat.total, 0)
  const solde = totalIncome - totalExpenses

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-stone-100 via-rose-50 to-blue-50">
        <div className="text-center">
          <div className="inline-block animate-spin rounded-full h-12 w-12 border-b-2 border-emerald-400"></div>
          <p className="mt-4 text-slate-700">Chargement...</p>
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-stone-100 via-rose-50 to-blue-50">
      <Header
        profile={profileId}
        title={`${MONTH_NAMES[month - 1]} ${year}`}
        description="Gérez vos revenus et dépenses"
        showBack={true}
        backHref={`/budget/${year}`}
      />

      <main className="container mx-auto px-4 py-8 relative z-10 space-y-6">
        {/* Solde */}
        <Card className="relative bg-white/50 backdrop-blur-sm border border-white/60 shadow-lg rounded-2xl overflow-hidden">
          <div className={`absolute inset-0 bg-gradient-to-br ${solde >= 0 ? 'from-emerald-400/10 to-teal-400/10' : 'from-red-400/10 to-rose-400/10'} opacity-50`}></div>
          <CardHeader className="relative">
            <CardTitle className="text-sm font-semibold text-slate-700 uppercase tracking-wide mb-2">Solde</CardTitle>
            <div className="flex items-center gap-3">
              <div className={`w-12 h-12 rounded-xl ${solde >= 0 ? 'bg-gradient-to-br from-emerald-400 to-teal-500' : 'bg-gradient-to-br from-red-400 to-rose-500'} flex items-center justify-center shadow-md`}>
                {solde >= 0 ? <TrendingUp className="h-6 w-6 text-white" /> : <TrendingDown className="h-6 w-6 text-white" />}
              </div>
              <div>
                <div className={`text-3xl font-bold ${solde >= 0 ? 'text-emerald-700' : 'text-red-700'}`}>
                  {solde.toFixed(2)} €
                </div>
                <p className="text-sm text-slate-500">
                  Entrées: {totalIncome.toFixed(2)}€ - Dépenses: {totalExpenses.toFixed(2)}€
                </p>
              </div>
            </div>
          </CardHeader>
        </Card>

        {/* Entrées (Revenus) */}
        <Card className="bg-white/50 backdrop-blur-sm border border-white/60 shadow-lg rounded-2xl overflow-hidden">
          <CardHeader className="border-b border-slate-100 bg-gradient-to-r from-blue-50/30 to-indigo-50/30">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <DollarSign className="h-5 w-5 text-blue-500" />
                <CardTitle className="text-lg font-bold text-slate-800">Entrées</CardTitle>
                <span className="text-sm text-slate-500">({totalIncome.toFixed(2)}€)</span>
              </div>
              <Button
                onClick={() => setShowIncomeForm(!showIncomeForm)}
                size="sm"
                className="bg-gradient-to-r from-blue-400 to-indigo-400 hover:from-blue-500 hover:to-indigo-500 text-white border-0 shadow-md"
              >
                <Plus className="h-4 w-4 mr-1" />
                Ajouter
              </Button>
            </div>
          </CardHeader>
          <CardContent className="p-4">
            {showIncomeForm && (
              <form onSubmit={handleAddIncome} className="mb-4 p-4 bg-blue-50/50 rounded-xl space-y-3">
                <input
                  type="text"
                  placeholder="Description (ex: Salaire, CAF...)"
                  value={newIncome.description}
                  onChange={(e) => setNewIncome({ ...newIncome, description: e.target.value })}
                  className="w-full px-3 py-2 rounded-lg border border-slate-200 focus:outline-none focus:ring-2 focus:ring-blue-400"
                  required
                />
                <input
                  type="number"
                  step="0.01"
                  placeholder="Montant"
                  value={newIncome.amount}
                  onChange={(e) => setNewIncome({ ...newIncome, amount: e.target.value })}
                  className="w-full px-3 py-2 rounded-lg border border-slate-200 focus:outline-none focus:ring-2 focus:ring-blue-400"
                  required
                />
                <div className="flex gap-2">
                  <Button type="submit" className="bg-blue-500 hover:bg-blue-600 text-white">
                    Confirmer
                  </Button>
                  <Button
                    type="button"
                    variant="outline"
                    onClick={() => {
                      setShowIncomeForm(false)
                      setNewIncome({ description: "", amount: "" })
                    }}
                  >
                    Annuler
                  </Button>
                </div>
              </form>
            )}
            {incomes.length === 0 ? (
              <p className="text-center py-6 text-slate-500">Aucune entrée pour ce mois</p>
            ) : (
              <div className="space-y-2">
                {incomes.map((income) => (
                  <div
                    key={income.id}
                    className="flex items-center justify-between p-3 bg-white rounded-lg shadow-sm hover:shadow-md transition-shadow"
                  >
                    <div>
                      <p className="font-medium text-slate-800">{income.description}</p>
                      <p className="text-xs text-slate-500">
                        {new Date(income.date).toLocaleDateString("fr-FR")}
                      </p>
                    </div>
                    <div className="flex items-center gap-3">
                      <span className="text-lg font-bold text-blue-600">+{income.amount.toFixed(2)}€</span>
                      <Button
                        variant="ghost"
                        size="sm"
                        onClick={() => handleDeleteIncome(income.id)}
                        className="text-red-500 hover:text-red-700 hover:bg-red-50"
                      >
                        ×
                      </Button>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </CardContent>
        </Card>

        {/* Catégories de dépenses */}
        <Card className="bg-white/50 backdrop-blur-sm border border-white/60 shadow-lg rounded-2xl overflow-hidden">
          <CardHeader className="border-b border-slate-100 bg-gradient-to-r from-rose-50/30 to-pink-50/30">
            <div className="flex items-center justify-between">
              <CardTitle className="text-lg font-bold text-slate-800">Catégories de dépenses</CardTitle>
              <Button
                onClick={() => setShowCategoryForm(!showCategoryForm)}
                size="sm"
                className="bg-gradient-to-r from-rose-400 to-pink-400 hover:from-rose-500 hover:to-pink-500 text-white border-0 shadow-md"
              >
                <Plus className="h-4 w-4 mr-1" />
                Ajouter
              </Button>
            </div>
          </CardHeader>
          <CardContent className="p-4">
            {showCategoryForm && (
              <form onSubmit={handleAddCategory} className="mb-4 p-4 bg-rose-50/50 rounded-xl space-y-3">
                <input
                  type="text"
                  placeholder="Nom de la catégorie (ex: Alimentation, Santé...)"
                  value={newCategory.name}
                  onChange={(e) => setNewCategory({ ...newCategory, name: e.target.value })}
                  className="w-full px-3 py-2 rounded-lg border border-slate-200 focus:outline-none focus:ring-2 focus:ring-rose-400"
                  required
                />
                <div className="flex gap-2">
                  <Button type="submit" className="bg-rose-500 hover:bg-rose-600 text-white">
                    Confirmer
                  </Button>
                  <Button
                    type="button"
                    variant="outline"
                    onClick={() => {
                      setShowCategoryForm(false)
                      setNewCategory({ name: "", color: "#10b981" })
                    }}
                  >
                    Annuler
                  </Button>
                </div>
              </form>
            )}
            {categories.length === 0 ? (
              <p className="text-center py-6 text-slate-500">Aucune catégorie pour ce mois</p>
            ) : (
              <div className="space-y-2">
                {categories.map((category) => (
                  <div
                    key={category.id}
                    className="flex items-center justify-between p-3 bg-white rounded-lg shadow-sm hover:shadow-md transition-all cursor-pointer"
                    onClick={() => router.push(`/budget/${year}/${month}/${category.id}`)}
                  >
                    <div className="flex items-center gap-3">
                      <div
                        className="w-10 h-10 rounded-lg flex items-center justify-center text-white font-bold shadow-sm"
                        style={{ backgroundColor: category.color || "#10b981" }}
                      >
                        {category.name.charAt(0)}
                      </div>
                      <p className="font-medium text-slate-800">{category.name}</p>
                    </div>
                    <div className="flex items-center gap-2">
                      <span className="text-lg font-bold text-slate-800">{category.total.toFixed(2)}€</span>
                      <span className="text-slate-400">→</span>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </CardContent>
        </Card>
      </main>
    </div>
  )
}
